#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########

set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get autoremove -y

# install requirements
apt-get install -y curl zenity

# install plymouth
apt-get install -y plymouth

# install wayfire & shell components
apt-get install -y labwc xwayland swaybg

# install & enable pipewire
apt-get install -y pipewire pipewire-pulse
#systemctl enable pipewire.service

# install additional tools
apt-get install -y alacritty

# install & configure lightdm
apt-get install -y lightdm
systemctl enable lightdm.service
systemctl --quiet set-default graphical.target

# enable autologin
groupadd -r autologin
usermod -aG autologin "${BASE_USER}"

# Unpack root at the end, so files are modified before
unpack /filesystem/root /
