name: "Get Project Version"
on:
  workflow_call:
    outputs:
      version:
        description: "The Project Version Number"
        value: ${{ jobs.get_version.outputs.version }}

jobs:
  get_version:
    name: "Get Version"
    runs-on: Ubuntu-22.04
    outputs:
      version: ${{ steps.store_version.outputs.version }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Store Version"
        id: store_version
        run: echo $(grep -oP '^export DIST_VERSION=\K.*' src/config) >> "$GITHUB_OUTPUT"